### PR TITLE
feat: Support new file contribution

### PR DESCRIPTION
**Pull request by jdneo**
1. If there is a active text editor and it's uri belongs to a workspace folder, then generate a new class at the same folder
2. Otherwise, ask user to select target project (if multiple) and package
3. If no project is opened, ask user to create a new project

resolve https://github.com/microsoft/vscode-java-pack/issues/706

### CODE REVIEW

**Comment by Eskibear** [comment]
LGTM, and suggest to support full qualified class name in future?

**Comment by jdneo** [comment]
Change the logic to:

1. If current active editor is on the project source path, create a file under the directory of the active editor
2. Otherwise, create an untitled file with a simple new Java class snippet.

**Review by Eskibear — DISMISSED** [review]

**Comment by jdneo** [comment]
Appended a commit. Now if there is no active text editor but having one source path, the source path will be returned as the package path. This is useful in invisible projects.

**Comment by jdneo** [comment]
Yes it's unstable

**Review by Eskibear — APPROVED** [review]

**Comment by jdneo** [comment]
We might need to revisit this feature once we can get the selected file path from the file explorer. See: https://github.com/microsoft/vscode/issues/3553

**Pull request merged**
