### PR TITLE
feat: Support creating new files/folders in Java Project explorer

### LINKED ISSUE #598: Support creating new files/folders in Java Project explorer
feedback from user survey:

_in project explorer, in Java Projects Tab I cannot create html file or folder or POM file_

### PR DESCRIPTION
**Pull request by jdneo**
fix #598

image

### CODE REVIEW

**Comment by izilongwan** [comment]
image
无法创建包?

**Comment by jdneo** [comment]
@izilongwan Please make sure your VS Code is 1.77 or higher

**Comment by izilongwan** [comment]
image
为啥还有版本限制

**Comment by jdneo** [comment]
Upstream API changes, see: https://github.com/microsoft/vscode/issues/175540#issuecomment-1494256462

**Comment by izilongwan** [comment]
标注下最低支持的版本吧

**Pull request merged**
